
package ec.edu.espe.HOManagment.view;

/**
 *
 * @author Code Warriors, DCCO-ESPE
 */
public class FrmHelp extends javax.swing.JFrame {

    public class centerFrame extends javax.swing.JFrame {

        public centerFrame() {
            initComponents();

            setLocationRelativeTo(null);
        }
    }

    /**
     * Creates new form FrmHelp
     */
    public FrmHelp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        txtOK1 = new javax.swing.JButton();
        txtSupport = new javax.swing.JTextField();
        txtEdison = new javax.swing.JTextField();
        txtLeonel = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtMailTipan = new javax.swing.JTextField();
        txtNumberTipan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(69, 91, 118));
        jPanel4.setMinimumSize(new java.awt.Dimension(649, 242));
        jPanel4.setPreferredSize(new java.awt.Dimension(978, 550));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOK1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtOK1.setText("Aceptar");
        txtOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOK1ActionPerformed(evt);
            }
        });
        jPanel4.add(txtOK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 90, -1));

        txtSupport.setBackground(new java.awt.Color(105, 145, 172));
        txtSupport.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSupport.setForeground(new java.awt.Color(0, 51, 51));
        txtSupport.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSupport.setText("SOPORTE TÉCNICO:");
        jPanel4.add(txtSupport, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 200, 60));

        txtEdison.setBackground(new java.awt.Color(105, 145, 172));
        txtEdison.setForeground(new java.awt.Color(0, 51, 51));
        txtEdison.setText("Edison Verdesoto");
        jPanel4.add(txtEdison, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        txtLeonel.setBackground(new java.awt.Color(105, 145, 172));
        txtLeonel.setForeground(new java.awt.Color(0, 51, 51));
        txtLeonel.setText("Leonel Tipan");
        jPanel4.add(txtLeonel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        txtMail.setBackground(new java.awt.Color(105, 145, 172));
        txtMail.setForeground(new java.awt.Color(0, 51, 51));
        txtMail.setText("Correo: edisondamian12@gmail.com");
        jPanel4.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        txtNumber.setBackground(new java.awt.Color(105, 145, 172));
        txtNumber.setForeground(new java.awt.Color(0, 51, 51));
        txtNumber.setText("Whatsapp: 0998621890");
        jPanel4.add(txtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        txtMailTipan.setBackground(new java.awt.Color(105, 145, 172));
        txtMailTipan.setText("leonel06tipan@gmail.com");
        txtMailTipan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailTipanActionPerformed(evt);
            }
        });
        jPanel4.add(txtMailTipan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        txtNumberTipan.setBackground(new java.awt.Color(105, 145, 172));
        txtNumberTipan.setText("0996212323");
        jPanel4.add(txtNumberTipan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOK1ActionPerformed
        FrmHardwareStoreMenu frmStylesirelia;
        frmStylesirelia = new FrmHardwareStoreMenu();
        frmStylesirelia.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_txtOK1ActionPerformed

    private void txtMailTipanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailTipanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailTipanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHelp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtEdison;
    private javax.swing.JTextField txtLeonel;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtMailTipan;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtNumberTipan;
    private javax.swing.JButton txtOK1;
    private javax.swing.JTextField txtSupport;
    // End of variables declaration//GEN-END:variables
}
